### PR TITLE
Update Core with the latest source and add some more translations

### PR DESCRIPTION
**Pull request by Alir3z4**

### CODE REVIEW

**Comment by Alir3z4** [comment]
Let me know if this looks good by you.
Once merge, I'll me adding more and more translations to it.

I have noticed the source is not updated with the latest of the flarum official ext english, so I've updated and added some more translation texts to it.

I'm trying to get more and more of it done through the week and make small pull request so you can get merge them and review for any possible mistakes that I might have.

**Comment by sijad** [comment]
Thanks man! 🙏

could you please revert back comments? I guess they've removed by a linter or something.

**Comment by Alir3z4** [comment]
Oh I see.
I'll revert them back and update.

You're correct, seems they have been removed by the trans app.

**Comment by Alir3z4** [comment]
I got all the comments back as well

**Comment by sijad** [comment]
well done.

**Pull request merged**
